# Generated by Django 4.1.5 on 2023-02-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('react', '0003_alter_expense_user_id_alter_income_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
